### ISSUE TITLE
Very Low time step when running with OpenFOAM 2.2.2

### ISSUE THREAD

**Issue by meouda** [petebachant/waveFlapper-OpenFOAM#1]
Dear Sir,

I am trying to run this case with OpenFOAM 2.2.2. Although I managed to run it but the resulting time step is very low (in order of 10e-08). Is that the normal situation or there is something wrong with my setup?

Best regards.

**Comment by sdzahedi** [comment]
Hello Sir, 
I am trying to run this case and after I blockMesh this case, It cannot be running and gives this error:
--> FOAM FATAL IO ERROR: 
cannot find file
I appreciate if you give me advice and  help me running this case finally.
Thanks

**Comment by petebachant** [comment]
@meouda, sorry for the late reply. I did not even see this issue! Did you end up getting this working? It sounds like the solver went unstable.

@sdzahedi, can you open a new issue and post the whole error message?

**Comment by petebachant** [comment]
Closing since this is very old and OpenFOAM has had many versions since 2.2.
