### ISSUE TITLE
running issue

### ISSUE THREAD

**Issue by sdzahedi** [petebachant/waveFlapper-OpenFOAM#3]
Hello Pete,
Thanks for your reply...
This is the error when I type  interDyMFoam and entered I ve faced:

Mesh OK.

End

sz@sz-Inspiron-560:~/Desktop/waveFlapper-OpenFOAM-master$ interDyMFoam
/_---------------------------------------------------------------------------_\
| =========                 |                                                 |
| \      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \    /   O peration     | Version:  2.4.0                                 |
|   \  /    A nd           | Web:      www.OpenFOAM.org                      |
|    \/     M anipulation  |                                                 |
*---------------------------------------------------------------------------*/
Build  : 2.4.0-f0842aea0e77
Exec   : interDyMFoam
Date   : Feb 19 2016
Time   : 16:45:25
Host   : "sz-Inspiron-560"
PID    : 2660
Case   : /home/sz/Desktop/waveFlapper-OpenFOAM-master
nProcs : 1
sigFpe : Enabling floating point exception trapping (FOAM_SIGFPE).
fileModificationChecking : Monitoring run-time modified files using timeStampMaster
allowSystemOperations : Allowing user-supplied system call operations

// \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* \* //
Create time

Create mesh for time = 0

Selecting dynamicFvMesh dynamicMotionSolverFvMesh
Selecting motion solver: displacementLaplacian
Selecting motion diffusion: inverseDistance
--> FOAM Warning : 
    From function polyBoundaryMesh::patchSet(const wordReList&, const bool, const bool) const
    in file meshes/polyMesh/polyBoundaryMesh/polyBoundaryMesh.C at line 815
    Cannot find any patch or group names matching flapper

PIMPLE: Operating solver in PISO mode

Reading field p_rgh

Reading field U

Reading/calculating face flux field phi

Reading transportProperties

--> FOAM FATAL IO ERROR: 
cannot find file

file: /home/sz/Desktop/waveFlapper-OpenFOAM-master/0/alpha.water at line 0.

```
From function regIOobject::readStream()
in file db/regIOobject/regIOobjectRead.C at line 73.
```

FOAM exiting

sz@sz-Inspiron-560:~/Desktop/waveFlapper-OpenFOAM-master$

**Comment by petebachant** [comment]
Are you using the `Allrun` script? I recommend doing so, as it wraps all meshing and running into a single call:

```
./Allrun
```

**Comment by sdzahedi** [comment]
Well done, I could run the case with Allrun script. Thank you Pete...
I want to model periodic wave in a flume which there will be two layer waters with different salinity and temperature. The periodic wave at the end of the flume will break on a slope. I am wondering if your code can be modified for this case either.
Many thanks and I am looking forward to hearing from you soon.

**Comment by petebachant** [comment]
If you need buoyancy forces due to temperature you will need a different solver. I'm not sure if there is one in OpenFOAM that solves for temperature and volume fraction for three different phases. Best to check the forums at http://cfd-online.com.
