### ISSUE TITLE
running issue

### ISSUE THREAD

**Issue by sdzahedi** [petebachant/waveFlapper-OpenFOAM#4]
Hello Pete,
I am facing this issue when I run the case. I use the command  ./Allrun but after few seconds It exits and there is no result or time steps in the folder. Many thanks and I appreciate your consideration and advice...

sz@sz-Inspiron-560:~/Desktop/waveFlapper-OpenFOAM-master$ ./Allrun
Running blockMesh on /home/sz/Desktop/waveFlapper-OpenFOAM-master
Running snappyHexMesh on /home/sz/Desktop/waveFlapper-OpenFOAM-master
Running setFields on /home/sz/Desktop/waveFlapper-OpenFOAM-master
Running interDyMFoam on /home/sz/Desktop/waveFlapper-OpenFOAM-master
sz@sz-Inspiron-560:~/Desktop/waveFlapper-OpenFOAM-master$

**Comment by petebachant** [comment]
Please post the end of `log.interDyMFoam`. I imagine the case is blowing up, like in #1. Also let me know what version of OpenFOAM you are running.

**Comment by sdzahedi** [comment]
--> FOAM FATAL IO ERROR: 
keyword div(((rho_nuEff)_dev2(T(grad(U))))) is undefined in dictionary "/home/sz/waveFlapper-OpenFOAM-master/system/fvSchemes.divSchemes"

file: /home/sz/waveFlapper-OpenFOAM-master/system/fvSchemes.divSchemes from line 30 to line 33.

```
From function dictionary::lookupEntry(const word&, bool, bool) const
in file db/dictionary/dictionary.C at line 442.
```

FOAM exiting

**Comment by sdzahedi** [comment]
Hello Pete,
I am using openfoam Version 3.0.1, released 15/12/15... parafoam 44.
Thanks

**Comment by petebachant** [comment]
That error gives the clue on what to fix. For running with OpenFOAM 3 and above, in `system/fvSchemes` you will need to change the div scheme name

``` c++
div(((rhonuEff)dev(T(grad(U)))))
```

to

``` c++
div(((rhonuEff)dev2(T(grad(U)))))
```

Or you can leave both, which will allow running both 2.x and 3.x.

**Comment by sdzahedi** [comment]
I am getting the same error, after I have changed the div...

--> FOAM FATAL IO ERROR: 
keyword div(((rho_nuEff)_dev2(T(grad(U))))) is undefined in dictionary "/home/sz/waveFlapper-OpenFOAM-master/system/fvSchemes.divSchemes"

file: /home/sz/waveFlapper-OpenFOAM-master/system/fvSchemes.divSchemes from line 31 to line 37.

```
From function dictionary::lookupEntry(const word&, bool, bool) const
in file db/dictionary/dictionary.C at line 442.
```

FOAM exiting

**Comment by sdzahedi** [comment]
this is what I have changed and added...

```
div(rhoPhi,U)  Gauss vanLeerV;
div(phi,alpha)  Gauss vanLeer;
div(phirb,alpha) Gauss vanLeer;
div(((rhonuEff)dev(T(grad(U)))));
div(((rhonuEff)dev2(T(grad(U)))));  
div((muEff*dev(T(grad(U))))) Gauss linear;
div((muEff*dev2(T(grad(U))))) Gauss linear;
```

**Comment by petebachant** [comment]
You need to specify the values for the keywords. Try:

```
div(rhoPhi,U)  Gauss vanLeerV;
div(phi,alpha)  Gauss vanLeer;
div(phirb,alpha) Gauss vanLeer;
div(((rhonuEff)dev2(T(grad(U))))) Gauss linear; // OpenFOAM 3.x
div((muEff*dev(T(grad(U))))) Gauss linear; // OpenFOAM 2.x
```

**Comment by petebachant** [comment]
Closing since this is now compatible with OpenFOAM 6 as of 16c9ea9.
