### ISSUE TITLE
fatal error when run with openFoam5.0

### ISSUE THREAD

**Issue by sunxu702** [petebachant/waveFlapper-OpenFOAM#5]
A fatal error "Cannot find file "points" in directory "polyMesh" in times 0 down to constant" when i run with openFoam 5.0. it seems that no blockMeshDict file under system or version unmatch? thank you for any advice.

**Comment by petebachant** [comment]
Good catch. I've only ever run this case with 2.3.x I believe. Can you submit a PR moving `blockMeshDict` from `constant/polyMesh` into `system`, and modifying `turbulenceProperties` per [this blog post](http://petebachant.me/updating-openfoam-case-files-for-30x/)?

**Comment by petebachant** [comment]
Should be resolved as of 16c9ea9.
